/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_projects_monitor_MonitorAct */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_projects_monitor_MonitorAct
#define _Included_com_zsy_frame_sample_jni_control_android_projects_monitor_MonitorAct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_monitor_MonitorAct
 * Method:    getPressure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_monitor_MonitorAct_getPressure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
