/* DO NOT EDIT THIS FILE - it is machine generated */
#include "samy_log.h"
#include "com_zsy_frame_sample_jni_control_android_projects_login_LoginEasyAct.h"

/**
 * 返回值 char* 这个代表char数组的首地址
 *  Jstring2CStr 把java中的jstring的类型转化成一个c语言中的char 字符串
 */
char* Jstring2CStr(JNIEnv* env, jstring jstr) {
	char* rtn = NULL;
	jclass clsstring = (*env)->FindClass(env, "java/lang/String");
	jstring strencode = (*env)->NewStringUTF(env, "GB2312");
	jmethodID mid = (*env)->GetMethodID(env, clsstring, "getBytes",
			"(Ljava/lang/String;)[B");
	jbyteArray barr = (jbyteArray)(*env)->CallObjectMethod(env, jstr, mid,
			strencode); // String .getByte("GB2312");
	jsize alen = (*env)->GetArrayLength(env, barr);
	jbyte* ba = (*env)->GetByteArrayElements(env, barr, JNI_FALSE);
	if (alen > 0) {
		rtn = (char*) malloc(alen + 1); //"\0"
		memcpy(rtn, ba, alen);
		rtn[alen] = 0;
	}
	(*env)->ReleaseByteArrayElements(env, barr, ba, 0); //
	return rtn;
}
int login(char* username, char* pwd) {
	// 连接网络发送数据给服务器,
	char* rightname = "samy";
	char* rightpwd = "123456";
	int i = 0;
	for (; username[i] != '\0'; i++) {
		if (username[i] != rightname[i])
			return 404;
	}
	return 200;
}

jint JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_login_LoginEasyAct_call_1login(
		JNIEnv * env, jobject obj, jstring jname, jstring jpwd) {
		char* cname = Jstring2CStr(env, jname);
		char* cpwd = Jstring2CStr(env, jpwd);
		LOGI("name =%s", cname);
		LOGI("pwd =%s", cpwd);

		return login(cname, cpwd);
	}
