/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_projects_login_LoginEasyAct */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_projects_login_LoginEasyAct
#define _Included_com_zsy_frame_sample_jni_control_android_projects_login_LoginEasyAct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_login_LoginEasyAct
 * Method:    call_login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_login_LoginEasyAct_call_1login
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
