/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct
#define _Included_com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct_convertmp3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_lame_FormatConversionAct_getLameVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
