/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_encrypt_signature_SignatureAct */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_encrypt_signature_SignatureAct
#define _Included_com_zsy_frame_sample_jni_control_android_encrypt_signature_SignatureAct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_encrypt_signature_SignatureAct
 * Method:    get_apk_signature
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_encrypt_signature_SignatureAct_get_1apk_1signature
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
