/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
#define _Included_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    StartRunning
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_StartRunning
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    StopRuning
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_StopRuning
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetWelcomInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetWelcomInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetRotateSpeed
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetRotateSpeed
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetVehicleSpeed
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetVehicleSpeed
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetWaterTemperature
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetWaterTemperature
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetAirDamper
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetAirDamper
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetTirePressure
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetTirePressure
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetOilMass
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetOilMass
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetOilWear
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetOilWear
  (JNIEnv *, jobject);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo
 * Method:    GetRemainingOil
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zsy_frame_sample_jni_control_android_projects_sannuo_RunningInfo_GetRemainingOil
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
