/* DO NOT EDIT THIS FILE - it is machine generated */
#include "samy_log.h"
#include <stdlib.h>
#include <bitmap.h>
#include <mem_utils.h>
#include "com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing.h"
static Bitmap bitmap;

jint JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeInitBitmap(
		JNIEnv* env, jobject thiz, jint width, jint height) {
	return initBitmapMemory(&bitmap, width, height);
}
void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeGetBitmapRow(
		JNIEnv* env, jobject thiz, jint y, jintArray pixels) {
	int cpixels[bitmap.width];
	getBitmapRowAsIntegers(&bitmap, (int) y, &cpixels);
	(*env)->SetIntArrayRegion(env, pixels, 0, bitmap.width, cpixels);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeSetBitmapRow
(JNIEnv* env, jobject thiz, jint y, jintArray pixels) {
	int cpixels[bitmap.width];
	(*env)->GetIntArrayRegion(env, pixels, 0, bitmap.width, cpixels);
	setBitmapRowFromIntegers(&bitmap, (int) y, &cpixels);
}

jint JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeGetBitmapWidth(
		JNIEnv* env, jobject thiz) {
	return bitmap.width;
}
jint JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeGetBitmapHeight(
		JNIEnv* env, jobject thiz) {
	return bitmap.height;
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeDeleteBitmap(JNIEnv* env, jobject thiz) {
	deleteBitmap(&bitmap);
}
jint JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeRotate90(
		JNIEnv* env, jobject thiz) {
	int resultCode = rotate90(&bitmap, 1, 1, 1);
	if (resultCode != MEMORY_OK) {
		return resultCode;
	}

	//All the component dimensions should have changed, so copy the correct dimensions
	bitmap.width = bitmap.redWidth;
	bitmap.height = bitmap.redHeight;
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeRotate180
( JNIEnv* env, jobject thiz) {
	rotate180(&bitmap, 1, 1, 1);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeFlipHorizontally
( JNIEnv* env, jobject thiz) {
	flipHorizontally(&bitmap, 1, 1, 1);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyInstafix
(JNIEnv* env, jobject thiz) {
	applyInstafix(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyAnsel
( JNIEnv* env, jobject thiz) {
	applyAnselFilter(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyTestino
( JNIEnv* env, jobject thiz) {
	applyTestino(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyXPro
( JNIEnv* env, jobject thiz) {
	applyXPro(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyRetro
( JNIEnv* env, jobject thiz) {
	applyRetro(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyBW
( JNIEnv* env, jobject thiz) {
	applyBlackAndWhiteFilter(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplySepia
( JNIEnv* env, jobject thiz) {
	applySepia(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyCyano
( JNIEnv* env, jobject thiz) {
	applyCyano(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyGeorgia
( JNIEnv* env, jobject thiz) {
	applyGeorgia(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplySahara
( JNIEnv* env, jobject thiz) {
	applySahara(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyHDR
( JNIEnv* env, jobject thiz) {
	applyHDR(&bitmap);
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeLoadResizedJpegBitmap
( JNIEnv* env, jobject thiz, jbyteArray bytes, jint jpegSize,
		jint maxPixels) {
	char* jpegData = (char*) (*env)->GetPrimitiveArrayCritical(env, bytes,
			NULL);

	if (jpegData == NULL) {
		LOGE("jpeg data was null");
		return JNI_GET_INT_ARRAY_ERROR;
	}

	int resultCode = decodeJpegData(jpegData, jpegSize, maxPixels, &bitmap);
	if (resultCode != MEMORY_OK) {
		deleteBitmap(&bitmap);
		LOGE("error decoding jpeg resultCode=%d", resultCode);
		return resultCode;
	}

	(*env)->ReleasePrimitiveArrayCritical(env, bytes, jpegData, 0);

	return MEMORY_OK;
}

void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeResizeBitmap
( JNIEnv* env, jobject thiz, jint newWidth, jint newHeight) {
	unsigned char* newRed;
	int resultCode = newUnsignedCharArray(newWidth * newHeight, &newRed);
	if (resultCode != MEMORY_OK) {
		return resultCode;
	}
	resizeChannelBicubic(bitmap.red, bitmap.width, bitmap.height, newRed,
			(int) newWidth, (int) newHeight);
	freeUnsignedCharArray(&bitmap.red);
	bitmap.red = newRed;
	bitmap.redWidth = newWidth;
	bitmap.redHeight = newHeight;

	unsigned char* newGreen;
	resultCode = newUnsignedCharArray(newWidth * newHeight, &newGreen);
	if (resultCode != MEMORY_OK) {
		return resultCode;
	}
	resizeChannelBicubic(bitmap.green, bitmap.width, bitmap.height, newGreen,
			(int) newWidth, (int) newHeight);
	freeUnsignedCharArray(&bitmap.green);
	bitmap.green = newGreen;
	bitmap.greenWidth = newWidth;
	bitmap.greenHeight = newHeight;

	unsigned char* newBlue;
	resultCode = newUnsignedCharArray(newWidth * newHeight, &newBlue);
	if (resultCode != MEMORY_OK) {
		return resultCode;
	}
	resizeChannelBicubic(bitmap.blue, bitmap.width, bitmap.height, newBlue,
			(int) newWidth, (int) newHeight);
	freeUnsignedCharArray(&bitmap.blue);
	bitmap.blue = newBlue;
	bitmap.blueWidth = newWidth;
	bitmap.blueHeight = newHeight;

	bitmap.width = newWidth;
	bitmap.height = newHeight;
}
