/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing */

#ifndef _Included_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
#define _Included_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeInitBitmap
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeInitBitmap
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeGetBitmapRow
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeGetBitmapRow
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeSetBitmapRow
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeSetBitmapRow
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeGetBitmapWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeGetBitmapWidth
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeGetBitmapHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeGetBitmapHeight
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeDeleteBitmap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeDeleteBitmap
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeRotate90
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeRotate90
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeRotate180
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeRotate180
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeFlipHorizontally
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeFlipHorizontally
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyInstafix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyInstafix
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyAnsel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyAnsel
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyTestino
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyTestino
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyXPro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyXPro
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyRetro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyRetro
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyBW
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyBW
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplySepia
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplySepia
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyCyano
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyCyano
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyGeorgia
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyGeorgia
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplySahara
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplySahara
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeApplyHDR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeApplyHDR
  (JNIEnv *, jclass);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeLoadResizedJpegBitmap
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeLoadResizedJpegBitmap
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing
 * Method:    nativeResizeBitmap
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zsy_frame_sample_jni_control_android_multimedia_image_filter_PhotoProcessing_nativeResizeBitmap
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
